'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceDedicacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceDedicacion.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As ServiceDedicacion.HelloWorldRequest) As ServiceDedicacion.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As ServiceDedicacion.HelloWorldRequest) As System.Threading.Tasks.Task(Of ServiceDedicacion.HelloWorldResponse)
        
        'CODEGEN: Generating message contract since element name asig from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerDedicacionMediaAsig", ReplyAction:="*")>  _
        Function obtenerDedicacionMediaAsig(ByVal request As ServiceDedicacion.obtenerDedicacionMediaAsigRequest) As ServiceDedicacion.obtenerDedicacionMediaAsigResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerDedicacionMediaAsig", ReplyAction:="*")>  _
        Function obtenerDedicacionMediaAsigAsync(ByVal request As ServiceDedicacion.obtenerDedicacionMediaAsigRequest) As System.Threading.Tasks.Task(Of ServiceDedicacion.obtenerDedicacionMediaAsigResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceDedicacion.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceDedicacion.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceDedicacion.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceDedicacion.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class obtenerDedicacionMediaAsigRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="obtenerDedicacionMediaAsig", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceDedicacion.obtenerDedicacionMediaAsigRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceDedicacion.obtenerDedicacionMediaAsigRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class obtenerDedicacionMediaAsigRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public asig As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal asig As String)
            MyBase.New
            Me.asig = asig
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class obtenerDedicacionMediaAsigResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="obtenerDedicacionMediaAsigResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceDedicacion.obtenerDedicacionMediaAsigResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceDedicacion.obtenerDedicacionMediaAsigResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class obtenerDedicacionMediaAsigResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public obtenerDedicacionMediaAsigResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal obtenerDedicacionMediaAsigResult As Integer)
            MyBase.New
            Me.obtenerDedicacionMediaAsigResult = obtenerDedicacionMediaAsigResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceDedicacion.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceDedicacion.WebService1Soap)
        Implements ServiceDedicacion.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceDedicacion_WebService1Soap_HelloWorld(ByVal request As ServiceDedicacion.HelloWorldRequest) As ServiceDedicacion.HelloWorldResponse Implements ServiceDedicacion.WebService1Soap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As ServiceDedicacion.HelloWorldRequest = New ServiceDedicacion.HelloWorldRequest()
            inValue.Body = New ServiceDedicacion.HelloWorldRequestBody()
            Dim retVal As ServiceDedicacion.HelloWorldResponse = CType(Me,ServiceDedicacion.WebService1Soap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceDedicacion_WebService1Soap_HelloWorldAsync(ByVal request As ServiceDedicacion.HelloWorldRequest) As System.Threading.Tasks.Task(Of ServiceDedicacion.HelloWorldResponse) Implements ServiceDedicacion.WebService1Soap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of ServiceDedicacion.HelloWorldResponse)
            Dim inValue As ServiceDedicacion.HelloWorldRequest = New ServiceDedicacion.HelloWorldRequest()
            inValue.Body = New ServiceDedicacion.HelloWorldRequestBody()
            Return CType(Me,ServiceDedicacion.WebService1Soap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceDedicacion_WebService1Soap_obtenerDedicacionMediaAsig(ByVal request As ServiceDedicacion.obtenerDedicacionMediaAsigRequest) As ServiceDedicacion.obtenerDedicacionMediaAsigResponse Implements ServiceDedicacion.WebService1Soap.obtenerDedicacionMediaAsig
            Return MyBase.Channel.obtenerDedicacionMediaAsig(request)
        End Function
        
        Public Function obtenerDedicacionMediaAsig(ByVal asig As String) As Integer
            Dim inValue As ServiceDedicacion.obtenerDedicacionMediaAsigRequest = New ServiceDedicacion.obtenerDedicacionMediaAsigRequest()
            inValue.Body = New ServiceDedicacion.obtenerDedicacionMediaAsigRequestBody()
            inValue.Body.asig = asig
            Dim retVal As ServiceDedicacion.obtenerDedicacionMediaAsigResponse = CType(Me,ServiceDedicacion.WebService1Soap).obtenerDedicacionMediaAsig(inValue)
            Return retVal.Body.obtenerDedicacionMediaAsigResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceDedicacion_WebService1Soap_obtenerDedicacionMediaAsigAsync(ByVal request As ServiceDedicacion.obtenerDedicacionMediaAsigRequest) As System.Threading.Tasks.Task(Of ServiceDedicacion.obtenerDedicacionMediaAsigResponse) Implements ServiceDedicacion.WebService1Soap.obtenerDedicacionMediaAsigAsync
            Return MyBase.Channel.obtenerDedicacionMediaAsigAsync(request)
        End Function
        
        Public Function obtenerDedicacionMediaAsigAsync(ByVal asig As String) As System.Threading.Tasks.Task(Of ServiceDedicacion.obtenerDedicacionMediaAsigResponse)
            Dim inValue As ServiceDedicacion.obtenerDedicacionMediaAsigRequest = New ServiceDedicacion.obtenerDedicacionMediaAsigRequest()
            inValue.Body = New ServiceDedicacion.obtenerDedicacionMediaAsigRequestBody()
            inValue.Body.asig = asig
            Return CType(Me,ServiceDedicacion.WebService1Soap).obtenerDedicacionMediaAsigAsync(inValue)
        End Function
    End Class
End Namespace
