'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Matriculas
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ehusw.es/jav/ServiciosWeb/comprobarmatricula.php?wsdl", ConfigurationName:="Matriculas.MatriculasPortType")>  _
    Public Interface MatriculasPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ehusw.es/jav/ServiciosWeb/comprobarmatricula.php/comprobar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function comprobar(ByVal x As String) As <System.ServiceModel.MessageParameterAttribute(Name:="z")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ehusw.es/jav/ServiciosWeb/comprobarmatricula.php/comprobar", ReplyAction:="*")>  _
        Function comprobarAsync(ByVal x As String) As <System.ServiceModel.MessageParameterAttribute(Name:="z")> System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MatriculasPortTypeChannel
        Inherits Matriculas.MatriculasPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MatriculasPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of Matriculas.MatriculasPortType)
        Implements Matriculas.MatriculasPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function comprobar(ByVal x As String) As String Implements Matriculas.MatriculasPortType.comprobar
            Return MyBase.Channel.comprobar(x)
        End Function
        
        Public Function comprobarAsync(ByVal x As String) As System.Threading.Tasks.Task(Of String) Implements Matriculas.MatriculasPortType.comprobarAsync
            Return MyBase.Channel.comprobarAsync(x)
        End Function
    End Class
End Namespace
